const cookies = [
  {
    domain: ".flytap.com",
    expirationDate: 1648741277,
    hostOnly: false,
    httpOnly: false,
    name: "__gads",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "ID=409afa1b4b5bff2b:T=1585669277:S=ALNI_MasTDdHbPo9Oi7PIdS6HuZUPw8Emw",
    id: 1,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1619538079,
    hostOnly: false,
    httpOnly: false,
    name: "__qca",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "P0-1697209138-1585669279347",
    id: 2,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1617205277.954232,
    hostOnly: false,
    httpOnly: false,
    name: "_abck",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "C5F1940E4FD93ECF83C67EDBBD7C047E~0~YAAQL3/NFwqdbhxxAQAAPAVBMQOV+uA5y/FU+rWxa+zju/qt9dx6EevVc9kFHx3cYSLpigRilPyhHxvMjzHtltioEDk2eDPJaf2mxM1grwMj99AyRdY/FoHxqPIr+ExOCE5aFlqOERIax57+KLRtfiFjQLhqT9kjuSUtnlK0BiNNZfZHsGFLt/KdX2cnq8NaRfCqaRHXyRnDqUnyk0HmAm8Vmx3UnnbcETM2uWyrRHn3QdyQaijnLTJiPzP2lOnoUCCNZ9YZAj6Ga9A6zkNbz+9BR0eiW8uPzEk1Moxj9XwF2ecsM6PkeLK1QHoDTyR674t/W3wZ/g==~-1~-1~-1",
    id: 3,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586826375,
    hostOnly: false,
    httpOnly: false,
    name: "_dc_gtm_UA-52936160-1",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 4,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418335,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_c_exps",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "",
    id: 5,
  },
  {
    domain: ".flytap.com",
    hostOnly: false,
    httpOnly: false,
    name: "_dy_csc_ses",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "t",
    id: 6,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_df_geo",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "Brazil..S%C3%A3o%20Paulo",
    id: 7,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_geo",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "BR.SA.BR_SP.BR_SP_S%C3%A3o%20Paulo",
    id: 8,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418335,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_ses_load_seq",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "21902%3A1586826335783",
    id: 9,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1618362335,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_soct",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1004240.1006053.1586826335",
    id: 10,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dy_toffset",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "-2",
    id: 11,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dycnst",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "dg",
    id: 12,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dycst",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "dk.w.c.ws.",
    id: 13,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1589418336,
    hostOnly: false,
    httpOnly: false,
    name: "_dyid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "2148217977324135580",
    id: 14,
  },
  {
    domain: ".flytap.com",
    hostOnly: false,
    httpOnly: false,
    name: "_dyjsession",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "004f62ec96665c7752228c3e7d7798bd",
    id: 15,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1594602346,
    hostOnly: false,
    httpOnly: false,
    name: "_fbp",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "fb.1.1585669278899.937972674",
    id: 16,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1649898339,
    hostOnly: false,
    httpOnly: false,
    name: "_ga",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.2.1090060768.1585669278",
    id: 17,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586826375,
    hostOnly: false,
    httpOnly: false,
    name: "_gat_UA-87635523-1",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 18,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1593445277,
    hostOnly: false,
    httpOnly: false,
    name: "_gcl_au",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1.1.2127369091.1585669278",
    id: 19,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586912739,
    hostOnly: false,
    httpOnly: false,
    name: "_gid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.2.580757918.1586809470",
    id: 20,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586828135,
    hostOnly: false,
    httpOnly: false,
    name: "_uetsid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "_uet74013f4f-6955-3254-026a-a0249ce573ab",
    id: 21,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586833513.752669,
    hostOnly: false,
    httpOnly: true,
    name: "ak_bmsc",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "68FAAE5AADBC8A008FF52356909690D3C900D93734710000470C955EF624DF08~pl2Gazu16vl2qhYO7tDn0PHKpL+GEkSmaGdgHaBPG5xXrtdkB7Y/DxjWvI5TfKg98sUtnkst9dK18syxsSwkXnLtSVEa7r1voRGwG23v6cvL8d+/Rv36RgcuAE1NS660x6OiAUrCqigD34tiktWu1/3dg+Bwu5S1fuAxHALQsuhL98dKy6nnvJa97GC//7EtMefjtXE7N1oFnKT02dRNaIZp0HYIX6T1FcqOAAxkPir7I=",
    id: 22,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586833514.578503,
    hostOnly: false,
    httpOnly: true,
    name: "bm_sv",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "B77A3319A7C697176CE1E09961E09AED~Yi2DtvfkcWuBEx9k5BI42nuTnrlwkL3owBdh3q4W3aPca9uxuxcZThv9zIJppWrJyn4VKvjeS7Jma5vYc/tP1CA6N0dlKhjo+jORiqprNNvncn1Zc+CCeX/uqDVZwB4geSAC/9x7A4FkUrSbl5x4KDdGKEzndQJLBRrpQWkpXNk=",
    id: 23,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1586840711.752782,
    hostOnly: false,
    httpOnly: true,
    name: "bm_sz",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "1E86585012E1A86EFBE4299BBCF5670C~YAAQN9kAyVbV7GRxAQAAFvs3dgfmTbHqB1QlWU4HI3xiN1rtN5Qh+Z4nia/qGzgXtiGP+Ej9OTWKwOfAdVdtMrQtpgPjK5t+1pj4TyYu/mOrWb9SV2WiCd2WV/lCjCxnNKmzA80EweVUwHNrAi//phfr+qogFnPxw0w1+TeRu08cCvAgSx44CsbDzt9P/VBj",
    id: 24,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1620990336,
    hostOnly: false,
    httpOnly: false,
    name: "cto_bundle",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "vpbaxl8zQzQwcUVCWkZNcXMzRDJPelk2NlhPekdxd0VxVDByMVJrU2FwVkJFMTZVeWE1R0VxWjNyQ0VFOVpMOHolMkZqak1oc3dydTcxdDV1YzV2VEVjUWNPR0twYzdtYWM2SXhTRzkzWG9QbVdFeVhCT0dqbXJ4dkV4blhxdGZpdldaVTNEbUJhTlRDSHdlNEZrTXV0Zkp0UTZGUSUzRCUzRA",
    id: 25,
  },
  {
    domain: ".flytap.com",
    expirationDate: 1673226340,
    hostOnly: false,
    httpOnly: false,
    name: "inside-eu",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "365877315-2d82d31956ba157ce63768f8b5451747ee6dca0d80c3c89fee7508dfde446514-0-0",
    id: 26,
  },
  {
    domain: ".flytap.com",
    hostOnly: false,
    httpOnly: false,
    name: "TLTSID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "UZP450O7GNEWLG8NOXIGIIRHYJKHRTFA",
    id: 27,
  },
  {
    domain: "book.flytap.com",
    hostOnly: true,
    httpOnly: true,
    name: "ASP.NET_SessionId",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "3lm24nstl11nibkndtx3dol5",
    id: 28,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1589454338.006993,
    hostOnly: true,
    httpOnly: true,
    name: "D_HID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1EA96A8F-FD17-323E-9AD2-372A13EA4C32",
    id: 29,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1589454338.005847,
    hostOnly: true,
    httpOnly: true,
    name: "D_IID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1E9560D5-40FC-355B-89F3-963D29DD68B0",
    id: 30,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1617206270.719204,
    hostOnly: true,
    httpOnly: true,
    name: "D_SID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "191.23.34.221:B8UJWBbdUmbxGngKs8DsekKz6dGw4n+BFTchCUejfjY",
    id: 31,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1589454338.006209,
    hostOnly: true,
    httpOnly: true,
    name: "D_UID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1DC8926E-62FC-3FAC-8EBE-8E9553E84CC3",
    id: 32,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1589454338.006514,
    hostOnly: true,
    httpOnly: true,
    name: "D_ZID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "11F90E47-1862-3936-B47D-F686655A9F2F",
    id: 33,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1589454338.006764,
    hostOnly: true,
    httpOnly: true,
    name: "D_ZUID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "56D31211-2080-3DAC-AC20-90B7C33A2BE7",
    id: 34,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1586829372.205344,
    hostOnly: true,
    httpOnly: true,
    name: "PointOfSale",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "market=BR&contract=TAPBR&_l=pt-br",
    id: 35,
  },
  {
    domain: "book.flytap.com",
    hostOnly: true,
    httpOnly: true,
    name: "R3AirStartCookie",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value:
      "departure=ORY&arrival=GRU&depDate=21.12.2020&depTime=0&retDate=25.12.2020&retTime=0&flightType=Return&depTimeType=&retTimeType=&paxAdt=1&paxChd=0&paxInf=0&paxSrc=&paxYth=&paxStu=&paxYad=0&resident=&cabinClass=Y&sort=SortPrice&depRadius=&arrRadius=&maxStopsNumber=&offerType=Standard&rooms=&TransactionDebug=_air_WebServices_Availability_TAPAvailability.asmx_GetOutboundFlights__2020_04_14_02_05",
    id: 36,
  },
  {
    domain: "book.flytap.com",
    hostOnly: true,
    httpOnly: true,
    name: "ReferrerCookie",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "ReferrerCookie=book.flytap.com",
    id: 37,
  },
  {
    domain: "book.flytap.com",
    expirationDate: 1586826672.205376,
    hostOnly: true,
    httpOnly: true,
    name: "stopover-banner",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "",
    id: 38,
  },
];

module.exports = cookies;
